### ISSUE TITLE
incorrect link of the The Internals of Spark SQL

### ISSUE THREAD

**Issue by Yikf** [japila-books/spark-sql-internals#9]
The `The Internals of Spark SQL` link  in README is incorrect, i was redirected to page 404

![image](https://user-images.githubusercontent.com/51110188/152936650-532d413a-43a8-4e51-be2d-1afec2c64b71.png)

**Comment by KarlManong** [comment]
I found a replacement link : https://books.japila.pl/spark-sql-internals/
